modLoader="javafml"
loaderVersion="[46,)"
license="MIT"
issueTrackerURL="https://github.com/PandaDap2006/Pandas-Falling-Trees/issues"
showAsResourcePack=false

[[mods]]
modId="fallingtrees"
version="${version}"
displayName="Panda's Falling Trees"
logoFile="icon.png"
description='''

'''

[[dependencies.fallingtrees]]
   modId="forge"
   mandatory=true
   versionRange="[46,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.fallingtrees]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20,1.21)"
   ordering="NONE"
   side="BOTH"
[[dependencies.fallingtrees]]
   modId="cloth_config"
   mandatory=true
   versionRange="[11.1.106,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.fallingtrees]]
   modId="architectury"
   mandatory=true
   versionRange="[9.1.12,)"
   ordering="NONE"
   side="BOTH"
