modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL="https://github.com/PandaDap2006/Pandas-Falling-Trees/issues"
license = "GPL-3"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modName}"
authors = "${modAuthor}"
description = '''
${modDescription}
'''
logoFile = "assets/${modId}/icon.png"

[[dependencies.${modId}]]
modId = "neoforge"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "minecraft"
mandatory = true
versionRange = "${neoForgeCompatibleVersions}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "architectury"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${modId}]]
modId="pandalib"
mandatory = true
versionRange = "[0.3,)"
ordering = "NONE"
side = "BOTH"