modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
showAsResourcePack=false
issueTrackerURL="https://github.com/PandaDap2006/Pandas-Falling-Trees/issues"

[[mods]]
	modId="fallingtrees"
	version="${version}"
	displayName="Falling Tree's"
	logoFile="icon.png"
	authors="The Panda Oliver/PandaMods"
	description='''
		Makes trees fall realistically.
	'''

[[dependencies.fallingtrees]]
   modId="forge"
   mandatory=true
   versionRange="[43,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.fallingtrees]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.19.2,1.19.3)"
   ordering="NONE"
   side="BOTH"
[[dependencies.fallingtrees]]
    modId="cloth_config"
    mandatory=true
    versionRange="[8.3.103,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.fallingtrees]]
    modId="architectury"
    mandatory=true
    versionRange="[6.5.85,)"
    ordering="NONE"
    side="BOTH"
