modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/PandaDap2006/Pandas-Falling-Trees/issues"
showAsResourcePack = false
license = "LGPL-3"

[[mods]]
modId = "fallingtrees"
version = "${version}"
displayName = "Falling Trees"
authors = "The Panda Oliver"
description = "Makes trees fall realistically."
logoFile = "icon.png"

[[dependencies.fallingtrees]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fallingtrees]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.19.3)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fallingtrees]]
modId = "architectury"
mandatory = true
versionRange = "[1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.fallingtrees]]
modId="pandalib"
mandatory=true
versionRange="[0.3,)"
ordering="NONE"
side="BOTH"

[[dependencies.fallingtrees]]
modId="treechop"
mandatory=false
versionRange="[0.18.6,)"
ordering="NONE"
side="BOTH"