modLoader="javafml"
loaderVersion="[44,)"
license="MIT"
issueTrackerURL="https://github.com/PandaDap2006/Pandas-Falling-Trees/issues"
showAsResourcePack=false

[[mods]]
modId="fallingtrees"
version="${version}"
displayName="Panda's Falling Trees"
logoFile="assets/fallingtrees/icon.png"
description='''

'''

[[dependencies.fallingtrees]]
   modId="forge"
   mandatory=true
   versionRange="[44,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.fallingtrees]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.19.3,1.21)"
   ordering="NONE"
   side="BOTH"
[[dependencies.fallingtrees]]
   modId="cloth_config"
   mandatory=true
   versionRange="[9.0.94,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.fallingtrees]]
   modId="architectury"
   mandatory=true
   versionRange="[7.1.86,)"
   ordering="NONE"
   side="BOTH"
