modLoader = "javafml"
loaderVersion = "[46,)"
issueTrackerURL = "https://github.com/PandaDap2006/Pandas-Falling-Trees/issues"
showAsResourcePack = false
license = "MIT"

[[mods]]
modId = "fallingtrees"
version = "${version}"
displayName = "Falling Trees"
authors = "The Panda Oliver/PandaMods"
description = "Makes trees fall realistically."
logoFile = "icon.png"

[[dependencies.fallingtrees]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fallingtrees]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fallingtrees]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.fallingtrees]]
modId="pandalib"
mandatory=true
versionRange="[0.2,)"
ordering="NONE"
side="BOTH"