modLoader = "javafml"
loaderVersion = "[2,)"
license = "LGPL-3"
issueTrackerURL="https://github.com/PandaDap2006/Pandas-Falling-Trees/issues"
showAsResourcePack=false

[[mods]]
modId = "fallingtrees"
version = "${version}"
displayName = "Falling Trees"
authors = "The Panda Oliver"
logoFile = "icon.png"
description = "Makes trees fall realistically."

[[dependencies.pandalib]]
modId = "neoforge"
type = "required"
versionRange = "[20.5.21-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pandalib]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.5,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pandalib]]
modId = "architectury"
type = "required"
versionRange = "[13,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.fallingtrees]]
modId="pandalib"
type = "required"
versionRange="[0.3,)"
ordering="NONE"
side="BOTH"

[[mixins]]
config = "fallingtrees-common.mixins.json"
[[mixins]]
config = "fallingtrees.mixins.json"