modLoader = "javafml"
loaderVersion = "*"
license = "GPL-3"
issueTrackerURL="https://github.com/PandaDap2006/Pandas-Falling-Trees/issues"

[[mods]]
modId = "fallingtrees"
version = "${version}"
displayName = "${name}"
authors = "The Panda Oliver"
logoFile = "assets/fallingtrees/icon.png"
description = "${description}"

[[dependencies.fallingtrees]]
modId = "neoforge"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.fallingtrees]]
modId = "minecraft"
type = "required"
versionRange = "${compatible_forgemc_versions}"
ordering = "NONE"
side = "BOTH"

[[dependencies.fallingtrees]]
modId = "architectury"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.fallingtrees]]
modId="pandalib"
type = "required"
versionRange="[0.3,)"
ordering="NONE"
side="BOTH"

[[mixins]]
config = "fallingtrees-common.mixins.json"
[[mixins]]
config = "fallingtrees.mixins.json"