name: Mod Publishing

on:
  push:
    branches:
      - "Stable/**"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/openjdk/jdk:21-ubuntu
      options: --user root

    steps:
      - uses: actions/checkout@v4

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Publish mod
        run: ./gradlew build publishMods
        env:
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
          MODRINTH_API_KEY: ${{ secrets.MODRINTH_API_KEY }}
          GITHUB_API_KEY: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}